# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Docker build
      run: |
        docker build -t cicdexample .
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker tag cicdexample hannut1/cicdexample:${GITHUB_SHA::7}
        docker push hannut1/cicdexample:${GITHUB_SHA::7}
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-36-114-217.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker pull hannut1/cicdexample:${GITHUB_SHA::7}
          docker tag hannut1/cicdexample:${GITHUB_SHA::7} cicdexample
          docker stop server
          docker run -d --rm --name server -p 80:3000 cicdexample
